name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: echo "${{toJSON(github.event)}}"
      - run: flutter build web --release
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "REF:${{github.event.head_commit.message }} - ${{ github.sha }}"
      - run: git push origin HEAD:gh-pages --force